version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run coverage:coveralls
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release
