version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test and Validate Coverage
          command: mkdir -p coverage && npm run coverage:ci
      - run:
          name: Publish Coverage
          command: npm run coverage:publish
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release
          command: npm run semantic-release
